version: '3'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "h0tch0c0l4t3!"
      ACCEPT_EULA: "Y"